#!/bin/bash
#
#    Copyright (C) 2012 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. See <http://www.gnu.org/licenses/gpl.html>

mydir=$(dirname "$(readlink -f "$0")")
logfile="$HOME/.config/logkeys.log" # $HOME is still users' even with sudo
touch "$logfile"
chown "$(stat -c%u:%g "$HOME")" "$logfile"
chmod 600 "$logfile"
sudo logkeys --start -m "$mydir/pt_BR.map" -o "$logfile"
